With this change the earnIncome macro works on master. Without it one gets an error like: ``` rolls.ts:216 Uncaught (in promise) TypeError: rollOptions.has is not a function     at rolls.ts:216:29     at CheckPF2e.roll (rolls.ts:236:11)     at runEarnIncome (eval at _executeScript (foundry.js:19865:16), <anonymous>:106:25)     at Object.callback (eval at _executeScript (foundry.js:19865:16), <anonymous>:204:25)     at Dialog.submit (foundry.js:54800:35)     at Dialog._onClickButton (foundry.js:54730:10)     at HTMLButtonElement.dispatch (jquery.min.js:2:43064)     at v.handle (jquery.min.js:2:41048)  ``` I have to admit that I don't understand why this change is required, .has on a Set *should* work. There's probably a better solution. To test it I used: ``` let pack = game.packs.get("pf2e.pf2e-macros"); await pack.getIndex().then((index) => { 	let id = index.find((e) => e.name === "Earn Income")?._id; 	if (id) { 		pack.getDocument(id).then((e) => e.execute()); 	} }); ```